### ISSUE TITLE
Vapoursynth R62 portable + Python 3.11 + vs-basicvsrpp ?

### ISSUE THREAD

**Issue by Selur** [HolyWu/vs-basicvsrpp#35]
Trying to get [vs-basicvsrpp](https://github.com/HolyWu/vs-basicvsrpp)+ running with  current Vapoursynth R62 and Python 3.11

Here's what I did, so far:
- created a folder named Vapoursynth
- downloaded https://www.python.org/ftp/python/3.11.3/python-3.11.3-embed-amd64.zip and extracted it into the folder
- downloaded https://github.com/vapoursynth/vapoursynth/releases/download/R62/VapourSynth64-Portable-R62.7z  and extracted it into the folder
- downloaded https://bootstrap.pypa.io/get-pip.py into the folder
- called `phyton get-pip.py`
- to python311._pth I added:
```
Scripts
Lib\site-packages
```
 - tried: `python -m pip install torch==1.13.1+cu117 torchvision==0.14.1+cu117 --extra-index-url https://download.pytorch.org/whl/cu117` that failed since there is no Python 3.11 support for it.
 -  called `python -m pip install torch===2.0.1+cu117 torchvision==0.15.2 -f https://download.pytorch.org/whl/torch_stable.html` which installed.
 - called `python -m pip install -U openmim`, which worked too.
 - called `python -m mim install "mmcv-full>=1.7.1"` which sadly failed, see: https://pastebin.com/R7PQFjVy
 
 Any idea how to get this working?

**Comment by soldivelot** [comment]
mmcv only provide 2.0.0 compiled version which support python 3.11

i try to install [mmcv-2.0.0-cp311-cp311-win_amd64.whl](https://download.openmmlab.com/mmcv/dist/cu118/torch2.0.0/mmcv-2.0.0-cp311-cp311-win_amd64.whl) and [mmengine-0.7.3-py3-none-any.whl](https://files.pythonhosted.org/packages/d8/d7/5fb7fac5b9420f956b69b3e197519995f6e38d5ef58291be3e3eb3306adf/mmengine-0.7.3-py3-none-any.whl) (mmcv-full is renamed to mmcv since v2.0)

then i find it isn't working

is there a mmcv-full 1.7.1 compiled for python 3.11?

**Comment by HolyWu** [comment]
Fixed.

**Comment by Selur** [comment]
Thanks, works fine! 👍
